// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXBDKdKAWab3DrHb23cv30tMRmMJ6BpU',
    appId: '1:511534859167:web:295765c16a00b4ec2ff3aa',
    messagingSenderId: '511534859167',
    projectId: 'quranapp-4a8f9',
    authDomain: 'quranapp-4a8f9.firebaseapp.com',
    storageBucket: 'quranapp-4a8f9.firebasestorage.app',
    measurementId: 'G-FH8158MG19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6yIPaUEx2RbPQFLCJ23ItaDkrj5l1lGU',
    appId: '1:511534859167:android:bb59a6afb481dca52ff3aa',
    messagingSenderId: '511534859167',
    projectId: 'quranapp-4a8f9',
    storageBucket: 'quranapp-4a8f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMGI7YXCsWVHU-4krzEyVGoIXs-olIHI',
    appId: '1:511534859167:ios:9af8876399ceb2ec2ff3aa',
    messagingSenderId: '511534859167',
    projectId: 'quranapp-4a8f9',
    storageBucket: 'quranapp-4a8f9.firebasestorage.app',
    iosBundleId: 'com.example.quranapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMGI7YXCsWVHU-4krzEyVGoIXs-olIHI',
    appId: '1:511534859167:ios:9af8876399ceb2ec2ff3aa',
    messagingSenderId: '511534859167',
    projectId: 'quranapp-4a8f9',
    storageBucket: 'quranapp-4a8f9.firebasestorage.app',
    iosBundleId: 'com.example.quranapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDXBDKdKAWab3DrHb23cv30tMRmMJ6BpU',
    appId: '1:511534859167:web:a2897ded901ad86a2ff3aa',
    messagingSenderId: '511534859167',
    projectId: 'quranapp-4a8f9',
    authDomain: 'quranapp-4a8f9.firebaseapp.com',
    storageBucket: 'quranapp-4a8f9.firebasestorage.app',
    measurementId: 'G-EDY2EC7EXL',
  );

}